import React, { useEffect } from "react";
import backgroundImage from "../Assets/Images/about-us.png";
import contactuscall from "../Assets/Icons/callus.svg";
import contactusemail from "../Assets/Icons/emailus.svg";

// import AboutUSComp from '../Components/AboutUSComp';
const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <>
      <div
        className="bg-cover bg-center h-[110vh] flex items-center justify-center"
        style={{ backgroundImage: `url(${backgroundImage})` }}
      >
        {/* Overlay Content */}
        <div className="relative flex flex-col items-center justify-center h-full text-white">
          <h1 className="text-5xl font-bold mb-4 text-center">
            Privacy Policy
          </h1>
        </div>
      </div>
      <div className="w-full p-4 md:p-24">
        <h1
          className="text-4xl font-bold mb-4 text-center md:text-left"
          style={{ color: "#20376D" }}
        >
          Alfa Privacy Policy
        </h1>
        <p className="text-lg mt-4" style={{ color: "#20376D" }}>
          ALFA (“we,” “our,” or “us”) is committed to protecting your privacy.
          This Privacy Policy explains how your personal information is
          collected, used, and disclosed by ALFA. This Privacy Policy applies to
          our website and its associated subdomains (collectively, our
          “Service”) alongside our application, ALFA. By accessing or using our
          Service, you signify that you have read, understood, and agree to our
          collection, storage, use, and disclosure of your personal information
          as described in this Privacy Policy and our Terms of Service.
        </p>
        <ul
          className="list-disc text-lg mt-8 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Definitions and Key Terms</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            To help explain things as clearly as possible in this Privacy
            Policy, every time any of these terms are referenced, they are
            strictly defined as:
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Cookies</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            A small amount of data generated by a website and saved by your web
            browser. It is used to identify your browser, provide analytics,
            remember information about you such as your language preference or
            login information.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Company</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            When this policy mentions “Company,” “we,” “us,” or “our,” it refers
            to ALFA, located at Prince Mansour Street, Dammam, Eastern Province,
            Saudi Arabia, that is responsible for your information under this
            Privacy Policy.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Country</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Where ALFA or the owners/founders of ALFA are based, in this case,
            Saudi Arabia.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Customer</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Refers to the company, organization, or person that signs up to use
            the ALFA Service to manage relationships with their consumers or
            service users.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Device</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Any internet-connected device such as a phone, tablet, computer, or
            any other device that can be used to visit ALFA and use the
            services.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">IP Address</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Every device connected to the Internet is assigned a number known as
            an Internet Protocol (IP) address. These numbers are usually
            assigned to geographic blocks. An IP address can often be used to
            identify the location from which a device is connecting to the
            Internet.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Personnel</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Refers to those individuals who are employed by ALFA or are under
            contract to perform a service on behalf of one of the parties.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Personal Data</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Any information that directly, indirectly, or in connection with
            other information—including a personal identification number—allows
            for the identification or identifiability of a natural person.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Service</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Refers to the service provided by ALFA as described in the relative
            terms (if available) and on this platform.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Third-party Service</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Refers to advertisers, contest sponsors, promotional and marketing
            partners, and others who provide our content or whose products or
            services we think may interest you.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">You</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            A person or entity that is registered with ALFA to use the Services.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-3xl">
            What Information Do We Collect?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We collect information from you when you visit our website, register
            on our site, place an order, subscribe to our newsletter, respond to
            a survey, or fill out a form.
          </p>
          <li className="text-lg mt-2">Name / Username</li>
          <li className="text-lg mt-2">Phone Numbers</li>
          <li className="text-lg mt-2">Email Addresses</li>
          <li className="text-lg mt-2">Mailing Addresses</li>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            When Does ALFA Use End User Information from Third Parties?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            ALFA will collect End User Data necessary to provide the ALFA
            services to our customers. End users may voluntarily provide us with
            information they have made available on social media websites. If
            you provide us with any such information, we may collect publicly
            available information from the social media websites you have
            indicated. You can control how much of your information social media
            websites make public by visiting these websites and changing your
            privacy settings.{" "}
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            When Does ALFA Use Customer Information from Third Parties?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We receive some information from third parties when you contact us.
            For example, when you submit your email address to us to show
            interest in becoming an ALFA customer, we receive information from a
            third party that provides automated fraud detection services to
            ALFA. We also occasionally collect information that is made publicly
            available on social media websites. You can control how much of your
            information social media websites make public by visiting these
            websites and changing your privacy settings.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            Do We Share the Information We Collect with Third Parties?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We may share the information that we collect, both personal and
            non-personal, with third parties such as advertisers, contest
            sponsors, promotional and marketing partners, and others who provide
            our content or whose products or services we think may interest you.
            We may also share it with our current and future affiliated
            companies and business partners. If we are involved in a merger,
            asset sale, or other business reorganization, we may also share or
            transfer your personal and non-personal information to our
            successors-in-interest.
            <br /><br /> We may engage trusted third-party service providers to
            perform functions and provide services to us, such as hosting and
            maintaining our servers and the website, database storage and
            management, email management, storage marketing, credit card
            processing, customer service, and fulfilling orders for products and
            services you may purchase through the website. We will likely share
            your personal information, and possibly some non-personal
            information, with these third parties to enable them to perform
            these services for us and for you.
            <br /><br /> While we strive to partner only with reputable third parties,
            ALFA is not responsible for any unauthorized actions, data misuse,
            or breaches that occur as a result of third-party negligence or
            factors beyond ALFA’s direct control. Users are encouraged to review
            the privacy policies of any third-party services they engage with
            through our platform. <br /><br />
            We may also disclose personal and non-personal information about you
            to government or law enforcement officials or private parties as we,
            in our sole discretion, believe necessary or appropriate to respond
            to claims, legal processes (including subpoenas), protect our rights
            and interests or those of a third party, the safety of the public or
            any person, to prevent or stop any illegal, unethical, or legally
            actionable activity, or to otherwise comply with applicable court
            orders, laws, rules, and regulations.
            <br /><br /> Under no circumstances shall ALFA be liable for third-party
            misuse of information beyond its control or for legal obligations
            imposed on third parties. ALFA will comply with the Saudi Data
            Protection Laws and ensure its actions align with the rights and
            obligations outlined therein.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            Where and When Is Information Collected from Customers and End
            Users?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            ALFA will collect personal information that you submit to us. We may
            also receive personal information about you from third parties as
            described above.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            How Do We Use the Information We Collect?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            Any of the information we collect from you may be used in one of the
            following ways:
          </p>
        </ul>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To personalize your experience (your information helps us to better
          liespond to your individual needs)
        </li>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To improve our website (we continually strive to improve our website
          lifferings based on the information and feedback we receive from you)
        </li>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
        </li>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To process transactions
        </li>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To administer a contest, promotion, survey, or other site feature
        </li>
        <li className="text-lg mt-4" style={{ color: "#20376D" }}>
          To send periodic emails
        </li>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            How Do We Use Your Email Address?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            By submitting your email address on this website, you agree to
            receive emails from us. You can cancel your participation in any of
            these email lists at any time by clicking on the opt-out link or
            other unsubscribe option included in the respective email. We only
            send emails to people who have authorized us to contact them, either
            directly or through a third party. We do not send unsolicited
            commercial emails, as we respect your privacy.{" "}
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            How Long Do We Keep Your Information?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We keep your information only so long as we need it to provide ALFA
            to you and fulfill the purposes described in this policy. When we no
            longer need to use your information and there is no need for us to
            keep it to comply with legal or regulatory obligations, we’ll either
            remove it from our systems or depersonalize it so that we cannot
            identify you.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            How Do We Protect Your Information?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
            submit, or access your personal information. All supplied
            sensitive/credit information is transmitted via Secure Socket Layer
            (SSL) technology and then encrypted into our Payment Gateway
            provider’s database only to be accessible by authorized personnel.
            However, no security system is foolproof, and we cannot guarantee
            the absolute security of your information.
            <br /><br /> Although we employ reasonable security measures, no system
            can be completely secure. ALFA shall not be held liable for breaches
            caused by factors beyond its reasonable control, including but not
            limited to cyberattacks, force majeure events, or user mishandling
            of sensitive information.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            Could Your Information Be Transferred to Other Countries?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            ALFA is incorporated in Saudi Arabia. Information collected via our
            website or from use of our help services may be transferred to our
            offices or personnel located throughout the world. By using our
            services, you consent to the trans-border transfer and hosting of
            such information.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            Is the Information Collected Through ALFA Secure?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            We take precautions to protect the security of your information.
            While we make reasonable efforts to protect your personal
            information, no security measure is completely foolproof. If
            applicable law imposes a non-disclaimable duty to protect your
            personal information, you agree that intentional misconduct will be
            the standard used to measure compliance.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">
            Can You Update or Correct Your Information?
          </p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            The rights you have to request updates or corrections to the
            information ALFA collects depend on your relationship with ALFA.
            Personnel may update or correct their information as detailed in our
            internal company employment policies. Customers can request updates
            or corrections to their information by contacting us directly.
          </p>
        </ul>
        <ul
          className="list-disc text-lg mt-4 list-inside text-sm space-y-1"
          style={{ color: "#20376D" }}
        >
          <p className="font-medium text-2xl">Limitation of Liability</p>
          <p className="text-lg mt-4" style={{ color: "#20376D" }}>
            ALFA shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of data, revenue,
            profits, or reputation, arising out of or related to the use or
            inability to use our Services, even if ALFA has been advised of the
            possibility of such damages.<br/><br /> ALFA’s responsibility for any claims
            relating to the Services is limited to the extent permissible under
            Saudi Data Protection Laws. Any data breach or misuse by third-party
            services engaged by ALFA shall not render ALFA liable if the breach
            or misuse occurs due to factors beyond its direct control or
            reasonable prevention measures. In case of such incidents, ALFA will
            promptly notify affected parties as required by Saudi Data
            Protection Laws and cooperate with authorities to mitigate any
            risks.
          </p>
        </ul>
      </div>
    </>
  );
};

export default PrivacyPolicy;
